version: "3.8"

services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    volumes:
      - static-data:/app/static
    expose:
      - "8000"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - ./frontend/.env
    expose:
      - "8080"

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - static-data:/etc/static

volumes:
  db-data:
  static-data:
