version: '3.9'

services:
  db:
    image: postgres:17.0-alpine3.20
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    command: ./start.sh
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    volumes:
      - backend_static:/app/static

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    restart: always
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_WEBSOCKET_BASE_URL: ${VITE_WEBSOCKET_BASE_URL}
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    volumes:
      - backend_static:/etc/static

volumes:
  postgres_data:
  backend_static:
